POST http://127.0.0.1:8005/api/v1/reservas
Content-Type: application/json

{
    "sala_id": 2,
    "solicitante_id": 2,
    "inicio_reserva": "2023-04-24",
    "fim_reserva": "2023-12-31",
    "dia": 2,
    "hora_inicio": "11:00:00",
    "hora_fim": "11:00:00"
}